### ISSUE TITLE
Number the tags?

### ISSUE THREAD

**Issue by vbrh-immalle** [alexthissen/BuildWebAPIsWorkshop#1]
It's not obvious which tags to checkout after `git checkout tags/Start` if you want to chronologically explore the app like you are doing on https://www.youtube.com/watch?v=ARIsfkhoRts. 

The best way I found so far is to just prefix the tags with `00_`, `01_`, ...

**Comment by vbrh-immalle** [comment]
To find the correct order, this comes close:

    git tag --sort=taggerdate

or

    git tag --format='%(refname) %(taggerdate)' --sort=taggerdate

**Comment by alexthissen** [comment]
Thanks for feedback. I have added new tags with v01 to v13 and kept the original ones. Does that make sense to you?

**Comment by vbrh-immalle** [comment]
Personally I'd like it even better if the tags would have a version **and** the description, like `v1_xyz` but you can consider this mainly as feedback for future repositories ;)

**Comment by alexthissen** [comment]
Thanks for the feedback. Will certainly consider that for next time.
